{ 'Philips 32PFL5404H':
   { name: 'Philips 32PFL5404H',
     roomName: 'Bedroom',
     roomKey: '6232364703679512576',
     adapterDeviceId: 'default',
     details:
      { sourceName: 'duiro',
        adapterName: 'tv',
        type: 'TV',
        manufacturer: 'Philips',
        name: '32PFL5404H',
        timing: [Object],
        deviceversion: 2,
        commandSets: [Array],
        deviceCapabilities: [],
        roles: [Array],
        capabilities: [],
        useTuner: false,
        icon: 'tv' },
     powerMode: 'default',
     macros:
      { BACK: [Object],
        'CHANNEL DOWN': [Object],
        'CHANNEL UP': [Object],
        'CURSOR DOWN': [Object],
        'CURSOR LEFT': [Object],
        'CURSOR RIGHT': [Object],
        'CURSOR UP': [Object],
        'DIGIT 0': [Object],
        'DIGIT 1': [Object],
        'DIGIT 2': [Object],
        'DIGIT 3': [Object],
        'DIGIT 4': [Object],
        'DIGIT 5': [Object],
        'DIGIT 6': [Object],
        'DIGIT 7': [Object],
        'DIGIT 8': [Object],
        'DIGIT 9': [Object],
        'CURSOR ENTER': [Object],
        'FORMAT AUTO': [Object],
        'FORMAT SCROLL': [Object],
        FORWARD: [Object],
        'FUNCTION BLUE': [Object],
        'FUNCTION GREEN': [Object],
        'FUNCTION RED': [Object],
        'FUNCTION YELLOW': [Object],
        GUIDE: [Object],
        INFO: [Object],
        'INPUT HDMI 1': [Object],
        'INPUT HDMI 2': [Object],
        'INPUT HDMI 3': [Object],
        'INPUT HDMI 4': [Object],
        'INPUT SCART 1': [Object],
        'INPUT TUNER 1': [Object],
        'INPUT VGA 1': [Object],
        MENU: [Object],
        'MENU HOME': [Object],
        'MUTE TOGGLE': [Object],
        OPTIONS: [Object],
        PAUSE: [Object],
        PLAY: [Object],
        'POWER OFF': [Object],
        'POWER ON': [Object],
        'POWER TOGGLE': [Object],
        'PREVIOUS CHANNEL': [Object],
        RECORD: [Object],
        REVERSE: [Object],
        'SMART PICTURE': [Object],
        'SMART SOUND': [Object],
        'INPUT SCROLL': [Object],
        STOP: [Object],
        SUBTITLE: [Object],
        TELETEXT: [Object],
        'VOLUME DOWN': [Object],
        'VOLUME UP': [Object] },
     genericMacros:
      { 'INPUT 1': [Object],
        'INPUT 10': [Object],
        'INPUT 2': [Object],
        'INPUT 3': [Object],
        'INPUT 4': [Object],
        'INPUT 5': [Object],
        'INPUT 6': [Object],
        'INPUT 7': [Object],
        'INPUT 8': [Object],
        'INPUT 9': [Object] },
     switches: {},
     sensors: {},
     sliders: {},
     textlabels: {},
     imageurls: {},
     procedures: {},
     directories: {},
     hypotheticalPowerState: 'off',
     favorites: [],
     capabilities:
      [ 'neeo.device.details.source-duiro',
        'neeo.device.needs-spec-update',
        'neeo.device.type.tv',
        'volume-step',
        'ir-button-guide',
        'neeo.feature.shortcuts',
        'neeo.feature.power-state-supported' ],
     key: '6368672848306765824',
     weight: 6368672848306766000 },
  Bedroom:
   { name: 'Bedroom',
     roomName: 'Bedroom',
     roomKey: '6232364703679512576',
     adapterDeviceId: '131074',
     details:
      { sourceName: 'neeo-deviceadapter',
        adapterName: 'apt-8f701fdfc5b6765bdc889b506f8b1aa601ca9d2b',
        type: 'LIGHT',
        manufacturer: 'IKEA',
        icon: 'light',
        name: 'Trådfri',
        timing: {},
        commandSets: [],
        deviceCapabilities: [Array],
        roles: [],
        capabilities: [] },
     powerMode: 'default',
     macros:
      { POWER_TOGGLE: [Object],
        'POWER OFF': [Object],
        'POWER ON': [Object] },
     genericMacros: {},
     switches: { power: [Object] },
     sensors:
      { BRIGHTNESS_SENSOR: [Object],
        POWER_SENSOR: [Object],
        powerstate: [Object] },
     sliders: { brightness: [Object] },
     textlabels: {},
     imageurls: {},
     procedures: {},
     directories: {},
     hypotheticalPowerState: 'off',
     favorites: [],
     capabilities:
      [ 'neeo.device.details.source-sdk-adapter',
        'neeo.device.type.light',
        'neeo.feature.bridge-device',
        'neeo.feature.grouped-device',
        'neeo.feature.shortcuts',
        'neeo.feature.power-state-supported' ],
     key: '6520067429790384128',
     weight: 6520067429790384000 },
  Vero:
   { name: 'Vero',
     roomName: 'Bedroom',
     roomKey: '6232364703679512576',
     adapterDeviceId: '04de7e80-d59c-4925-9024-9429facc335c',
     details:
      { sourceName: 'src-4fe66040340b0a870ba5a5cef275ca157cb22f3b',
        adapterName: 'apt-39267298a033579cf0e822c30ed906e922cb5b10',
        type: 'MUSICPLAYER',
        manufacturer: 'XBMC',
        driverVersion: 28,
        icon: 'musicplayer',
        name: 'Kodi',
        timing: {},
        commandSets: [],
        deviceCapabilities: [Array],
        roles: [],
        capabilities: [] },
     powerMode: 'default',
     macros:
      { BACK: [Object],
        'CHANNEL DOWN': [Object],
        'CHANNEL UP': [Object],
        CMD_ASPECTRATIO: [Object],
        CMD_AUDIODELAY: [Object],
        CMD_AUDIODELAYMINUS: [Object],
        CMD_AUDIODELAYPLUS: [Object],
        CMD_AUDIONEXTLANGUAGE: [Object],
        CMD_AUDIOTOGGLEDIGITAL: [Object],
        CMD_BACK: [Object],
        CMD_BACKSPACE: [Object],
        CMD_BIGSTEPBACK: [Object],
        CMD_BIGSTEPFORWARD: [Object],
        CMD_BLUE: [Object],
        CMD_CHANNELDOWN: [Object],
        CMD_CHANNELUP: [Object],
        CMD_CHAPTERORBIGSTEPBACK: [Object],
        CMD_CHAPTERORBIGSTEPFORWARD: [Object],
        CMD_CLOSE: [Object],
        CMD_CODECINFO: [Object],
        CMD_CONTEXTMENU: [Object],
        CMD_COPY: [Object],
        CMD_CREATEBOOKMARK: [Object],
        CMD_CREATEEPISODEBOOKMARK: [Object],
        CMD_CYCLESUBTITLE: [Object],
        CMD_DECREASERATING: [Object],
        CMD_DECREASEVISRATING: [Object],
        CMD_DELETE: [Object],
        CMD_DOWN: [Object],
        CMD_ENTER: [Object],
        CMD_ERROR: [Object],
        CMD_FASTFORWARD: [Object],
        CMD_FIRSTPAGE: [Object],
        CMD_FORWARD: [Object],
        CMD_FULLSCREEN: [Object],
        CMD_GREEN: [Object],
        CMD_GUIPROFILE: [Object],
        CMD_HIGHLIGHT: [Object],
        CMD_HOME: [Object],
        CMD_INCREASERATING: [Object],
        CMD_INCREASEVISRATING: [Object],
        CMD_INFO: [Object],
        CMD_LASTPAGE: [Object],
        CMD_LEFT: [Object],
        CMD_LOCKPRESET: [Object],
        CMD_MENU: [Object],
        CMD_MOVE: [Object],
        CMD_MOVEITEMDOWN: [Object],
        CMD_MOVEITEMUP: [Object],
        CMD_MUTE: [Object],
        CMD_NEXT: [Object],
        CMD_NEXTCHANNELGROUP: [Object],
        CMD_NEXTPRESET: [Object],
        CMD_NEXTRESOLUTION: [Object],
        CMD_NEXTSCENE: [Object],
        CMD_NEXTSTEREOMODE: [Object],
        CMD_NEXTSUBTITLE: [Object],
        CMD_NOOP: [Object],
        CMD_OSD: [Object],
        CMD_PAGEDOWN: [Object],
        CMD_PAGEUP: [Object],
        CMD_PARENTDIR: [Object],
        CMD_PARENTFOLDER: [Object],
        CMD_PAUSE: [Object],
        CMD_PLAY: [Object],
        CMD_PLAYERDEBUG: [Object],
        CMD_PLAYERPROCESSINFO: [Object],
        CMD_PLAYLIST: [Object],
        CMD_PLAYPAUSE: [Object],
        CMD_PLAYPVR: [Object],
        CMD_PLAYPVRRADIO: [Object],
        CMD_PLAYPVRTV: [Object],
        CMD_POWER_OFF: [Object],
        CMD_POWER_ON: [Object],
        CMD_PREVIOUS: [Object],
        CMD_PREVIOUSCHANNELGROUP: [Object],
        CMD_PREVIOUSMENU: [Object],
        CMD_PREVIOUSPRESET: [Object],
        CMD_PREVIOUSSCENE: [Object],
        CMD_PREVIOUSSTEREOMODE: [Object],
        CMD_QUEUE: [Object],
        CMD_RANDOMPRESET: [Object],
        CMD_RECORD: [Object],
        CMD_RED: [Object],
        CMD_RELOADKEYMAPS: [Object],
        CMD_RENAME: [Object],
        CMD_REVERSE: [Object],
        CMD_REWIND: [Object],
        CMD_RIGHT: [Object],
        CMD_SCANITEM: [Object],
        CMD_SCREENSHOT: [Object],
        CMD_SCROLLDOWN: [Object],
        CMD_SCROLLUP: [Object],
        CMD_SELECT: [Object],
        CMD_SETRATING: [Object],
        CMD_SETTINGSLEVELCHANGE: [Object],
        CMD_SETTINGSRESET: [Object],
        CMD_SHOWCODEC: [Object],
        CMD_SHOWOSD: [Object],
        CMD_SHOWPLAYERPROCESSINFO: [Object],
        CMD_SHOWPRESET: [Object],
        CMD_SHOWSUBTITLES: [Object],
        CMD_SHOWTIME: [Object],
        CMD_SHOWTIMERRULE: [Object],
        CMD_SHOWVIDEOMENU: [Object],
        CMD_SKIPNEXT: [Object],
        CMD_SKIPPREVIOUS: [Object],
        CMD_SMALLSTEPBACK: [Object],
        CMD_STEPBACK: [Object],
        CMD_STEPFORWARD: [Object],
        CMD_STEREOMODE: [Object],
        CMD_STEREOMODETOMONO: [Object],
        CMD_STOP: [Object],
        CMD_SWITCHPLAYER: [Object],
        CMD_TOGGLECOMMSKIP: [Object],
        CMD_TOGGLEFULLSCREEN: [Object],
        CMD_TOGGLESTEREOMODE: [Object],
        CMD_TOGGLEWATCHED: [Object],
        CMD_UP: [Object],
        CMD_VERTICALSHIFTDOWN: [Object],
        CMD_VERTICALSHIFTUP: [Object],
        CMD_VOLAMPDOWN: [Object],
        CMD_VOLAMPUP: [Object],
        CMD_VOLUMEAMPLIFICATION: [Object],
        CMD_VOLUMEDOWN: [Object],
        CMD_VOLUMEUP: [Object],
        CMD_WINDOW_FULLSCREEN_LIVE_TV: [Object],
        CMD_WINDOW_FULLSCREEN_VIDEO: [Object],
        CMD_WINDOW_HOME: [Object],
        CMD_WINDOW_MUSIC: [Object],
        CMD_WINDOW_TVRECORDINGS: [Object],
        CMD_WINDOW_VIDEOS: [Object],
        CMD_YELLOW: [Object],
        'CURSOR DOWN': [Object],
        'CURSOR ENTER': [Object],
        'CURSOR LEFT': [Object],
        'CURSOR RIGHT': [Object],
        'CURSOR UP': [Object],
        'DIGIT 0': [Object],
        'DIGIT 1': [Object],
        'DIGIT 2': [Object],
        'DIGIT 3': [Object],
        'DIGIT 4': [Object],
        'DIGIT 5': [Object],
        'DIGIT 6': [Object],
        'DIGIT 7': [Object],
        'DIGIT 8': [Object],
        'DIGIT 9': [Object],
        FORWARD: [Object],
        'FUNCTION BLUE': [Object],
        'FUNCTION GREEN': [Object],
        'FUNCTION RED': [Object],
        'FUNCTION YELLOW': [Object],
        LANGUAGE: [Object],
        LIVE: [Object],
        MENU: [Object],
        'MUTE TOGGLE': [Object],
        'MY RECORDINGS': [Object],
        NEXT: [Object],
        PAUSE: [Object],
        PLAY: [Object],
        'POWER OFF': [Object],
        'POWER ON': [Object],
        PREVIOUS: [Object],
        RECORD: [Object],
        REVERSE: [Object],
        'SKIP SECONDS BACKWARD': [Object],
        'SKIP SECONDS FORWARD': [Object],
        STOP: [Object],
        SUBTITLE: [Object],
        'VOLUME DOWN': [Object],
        'VOLUME UP': [Object] },
     genericMacros: {},
     switches: { SWITCH_MUTE: [Object] },
     sensors:
      { IMAGE_NOW_PLAYING_THUMBNAIL_LARGE_SENSOR: [Object],
        IMAGE_NOW_PLAYING_THUMBNAIL_SMALL_SENSOR: [Object],
        LABEL_NOW_PLAYING_CAPTION_SENSOR: [Object],
        LABEL_NOW_PLAYING_DESCRIPTION_SENSOR: [Object],
        SLIDER_VOLUME_SENSOR: [Object],
        SWITCH_MUTE_SENSOR: [Object] },
     sliders: { SLIDER_VOLUME: [Object] },
     textlabels:
      { LABEL_NOW_PLAYING_CAPTION: [Object],
        LABEL_NOW_PLAYING_DESCRIPTION: [Object] },
     imageurls:
      { IMAGE_NOW_PLAYING_THUMBNAIL_LARGE: [Object],
        IMAGE_NOW_PLAYING_THUMBNAIL_SMALL: [Object] },
     procedures: {},
     directories:
      { DIRECTORY_FAVOURITES: [Object],
        DIRECTORY_LIBRARY_AUDIO: [Object],
        DIRECTORY_LIBRARY_VIDEO: [Object],
        DIRECTORY_NOW_PLAYING: [Object],
        DIRECTORY_QUEUE: [Object],
        DIRECTORY_ROOT: [Object] },
     hypotheticalPowerState: 'on',
     favorites: [],
     capabilities:
      [ 'neeo.device.details.source-sdk-adapter',
        'neeo.device.type.musicplayer',
        'volume-step',
        'neeo.feature.queuedirectory-support',
        'neeo.feature.shortcuts',
        'neeo.feature.power-state-supported' ],
     key: '6537041770331504640',
     weight: 6537041770331505000 } }
{ sourceName: 'src-4fe66040340b0a870ba5a5cef275ca157cb22f3b',
  adapterName: 'apt-39267298a033579cf0e822c30ed906e922cb5b10',
  type: 'MUSICPLAYER',
  manufacturer: 'XBMC',
  driverVersion: 28,
  icon: 'musicplayer',
  name: 'Kodi',
  timing: {},
  commandSets: [],
  deviceCapabilities: [ 'register-user-account', 'register-user-account' ],
  roles: [],
  capabilities: [] }
