'use strict';

/*
 * https://github.com/xbmc/xbmc/blob/master/system/keymaps/keyboard.xml
 *
 * Caveat: Buttons in button groups have hardcoded IDs which also get listed
 *	as separate buttons in the app. For this reason, only other button IDs will
 *	have the CMD_ prefix. If you can live without them, comment out the button
 *	groups in kodiDvice.js for a less cluttered list.
 */

var commands = {

	/*
	 * These are required for the NEEO button groups
	 */

	// Color Buttons
	'FUNCTION RED': { name: 'Red button', method: 'Input.ExecuteAction', params: { action: 'red' } },
	'FUNCTION GREEN': { name: 'Green button', method: 'Input.ExecuteAction', params: { action: 'green' } },
	'FUNCTION YELLOW': { name: 'Yellow button', method: 'Input.ExecuteAction', params: { action: 'yellow' } },
	'FUNCTION BLUE': { name: 'Blue button', method: 'Input.ExecuteAction', params: { action: 'blue' } },
	// Controlpad (OK)
	'CURSOR UP': { name: 'Cursor up', method: 'Input.up' },
	'CURSOR DOWN': { name: 'Cursor down', method: 'Input.down' },
	'CURSOR LEFT': { name: 'Cursor left', method: 'Input.left' },
	'CURSOR RIGHT': { name: 'Cursor right', method: 'Input.right' },
	'CURSOR ENTER': { name: 'Select', method: 'Input.select' },
	// Numpad
	'DIGIT 0': { name: 'Digit 0', method: 'Input.ExecuteAction', params: { action: 'number0' } },
	'DIGIT 1': { name: 'Digit 1', method: 'Input.ExecuteAction', params: { action: 'number1' } },
	'DIGIT 2': { name: 'Digit 2', method: 'Input.ExecuteAction', params: { action: 'number2' } },
	'DIGIT 3': { name: 'Digit 3', method: 'Input.ExecuteAction', params: { action: 'number3' } },
	'DIGIT 4': { name: 'Digit 4', method: 'Input.ExecuteAction', params: { action: 'number4' } },
	'DIGIT 5': { name: 'Digit 5', method: 'Input.ExecuteAction', params: { action: 'number5' } },
	'DIGIT 6': { name: 'Digit 6', method: 'Input.ExecuteAction', params: { action: 'number6' } },
	'DIGIT 7': { name: 'Digit 7', method: 'Input.ExecuteAction', params: { action: 'number7' } },
	'DIGIT 8': { name: 'Digit 8', method: 'Input.ExecuteAction', params: { action: 'number8' } },
	'DIGIT 9': { name: 'Digit 9', method: 'Input.ExecuteAction', params: { action: 'number9' } },
	// Power
	'POWER ON': { name: 'Power on', method: 'WOL' },
	'POWER OFF': { name: 'Power off', method: 'System.Shutdown' },
	// Channel Zapper
	'CHANNEL UP': { name: 'Channel up', method: 'Input.ExecuteAction', params: { action: 'channelup' } },
	'CHANNEL DOWN': { name: 'Channel down', method: 'Input.ExecuteAction', params: { action: 'channeldown' } },
	// Transport (OK)
	'PLAY': { name: 'Play', method: 'Input.ExecuteAction', params: { action: 'playpause' } },
	'PAUSE': { name: 'Pause', method: 'Input.ExecuteAction', params: { action: 'pause' } },
	'STOP': { name: 'Stop', method: 'Input.ExecuteAction', params: { action: 'stop' } },
	// Transport Search (OK)
	'REVERSE': { name: 'Reverse', method: 'Player.SetSpeed', params: { playerid: 1, speed: -2 } },
	'FORWARD': { name: 'Forward', method: 'Player.SetSpeed', params: { playerid: 1, speed: 2 } },
	// Transport Scan (OK)
	'PREVIOUS': { name: 'Previous', method: 'Player.GoTo', params: { playerid: 1, to: 'previous' } },
	'NEXT': { name: 'Next', method: 'Player.GoTo', params: { playerid: 1, to: 'next' } },
	// Transport Skip (OK)
	'SKIP SECONDS BACKWARD': { name: 'Skip back', method: 'Input.ExecuteAction', params: { action: 'stepback' } },
	'SKIP SECONDS FORWARD': { name: 'Skip forward', method: 'Input.ExecuteAction', params: { action: 'stepforward' } },
	// Language
	'SUBTITLE': { name: 'Subtitle', method: 'Input.ExecuteAction', params: { action: 'nextsubtitle' } },
	'LANGUAGE': { name: 'Audio language', method: 'Input.ExecuteAction', params: { action: 'audionextlanguage' } },
	// Menu and Back (OK)
	'MENU': { name: 'Activate window: Home', method: 'GUI.ActivateWindow', params: { window: 'home' } },
	'BACK': { name: 'Back', method: 'Input.Back' },
	// Volume (OK)
	'VOLUME UP': { name: 'Volume up', method: 'Input.ExecuteAction', params: { action: 'volumeup' } },
	'VOLUME DOWN': { name: 'Volume down', method: 'Input.ExecuteAction', params: { action: 'volumedown' } },
	'MUTE TOGGLE': { name: 'Mute', method: 'Input.ExecuteAction', params: { action: 'mute' } },
	// Record (OK)
	'RECORD': { name: 'Record', method: 'Input.ExecuteAction', params: { action: 'record' } },
	'MY RECORDINGS': { name: 'My recordings', method: 'GUI.ActivateWindow', params: { window: 'tvrecordings' } },
	'LIVE': { name: 'Live', method: 'GUI.ActivateWindow', params: { window: 'fullscreenlivetv' } },

	/*
	 *	Input.* methods
	 */

	'CMD_BACK': { name: 'Back', method: 'Input.Back' },
	'CMD_CONTEXTMENU': { name: 'Context menu', method: 'Input.ContextMenu' },
	'CMD_HOME': { name: 'Home', method: 'Input.Home' },
	'CMD_INFO': { name: 'Info', method: 'Input.Info' },
	'CMD_SHOWCODEC': { name: 'Show codec info', method: 'Input.ShowCodec' },
	'CMD_SHOWOSD': { name: 'Show OSD', method: 'Input.ShowOSD' },
	'CMD_SHOWPLAYERPROCESSINFO': { name: 'Show player process info', method: 'Input.ShowPlayerProcessInfo' },
	'CMD_UP': { name: 'Cursor up', method: 'Input.up' },
 	'CMD_DOWN': { name: 'Cursor down', method: 'Input.down' },
 	'CMD_LEFT': { name: 'Cursor left', method: 'Input.left' },
 	'CMD_RIGHT': { name: 'Cursor right', method: 'Input.right' },
 	'CMD_SELECT': { name: 'Select', method: 'Input.select' },


	/*
	 * Input actions
	 * https://kodi.wiki/view/Action_IDs
	 * https://kodi.wiki/view/JSON-RPC_API/v9#Input.Action
	 */

	'CMD_RED': { name: 'Red button', method: 'Input.ExecuteAction', params: { action: 'red' } },
	'CMD_GREEN': { name: 'Green button', method: 'Input.ExecuteAction', params: { action: 'green' } },
	'CMD_YELLOW': { name: 'Yellow button', method: 'Input.ExecuteAction', params: { action: 'yellow' } },
	'CMD_BLUE': { name: 'Blue button', method: 'Input.ExecuteAction', params: { action: 'blue' } },
	'CMD_CHANNELUP': { name: 'Channel up', method: 'Input.ExecuteAction', params: { action: 'channelup' } },
 	'CMD_CHANNELDOWN': { name: 'Channel down', method: 'Input.ExecuteAction', params: { action: 'channeldown' } },
	'CMD_NEXTCHANNELGROUP': { name: 'Next channel group',  method: 'Input.ExecuteAction',  params: { action: 'nextchannelgroup' } },
	'CMD_PREVIOUSCHANNELGROUP': { name: 'Previous channel group',  method: 'Input.ExecuteAction',  params: { action: 'previouschannelgroup' } },
	'CMD_PLAY': { name: 'Play',  method: 'Input.ExecuteAction',  params: { action: 'play' } },
	'CMD_PLAYPAUSE': { name: 'Play', method: 'Input.ExecuteAction', params: { action: 'playpause' } },
	'CMD_PAUSE': { name: 'Pause', method: 'Input.ExecuteAction', params: { action: 'pause' } },
	'CMD_STOP': { name: 'Stop', method: 'Input.ExecuteAction', params: { action: 'stop' } },
	'CMD_RECORD': { name: 'Record', method: 'Input.ExecuteAction', params: { action: 'record' } },
	'CMD_FASTFORWARD': { name: 'Fast forward',  method: 'Input.ExecuteAction',  params: { action: 'fastforward' } },
	'CMD_REWIND': { name: 'Rewind',  method: 'Input.ExecuteAction',  params: { action: 'rewind' } },
	'CMD_BIGSTEPFORWARD': { name: 'Big step forward',  method: 'Input.ExecuteAction',  params: { action: 'bigstepforward' } },
	'CMD_BIGSTEPBACK': { name: 'Big step back',  method: 'Input.ExecuteAction',  params: { action: 'bigstepback' } },
	'CMD_CHAPTERORBIGSTEPFORWARD': { name: 'Chapter or big step forward',  method: 'Input.ExecuteAction',  params: { action: 'chapterorbigstepforward' } },
	'CMD_CHAPTERORBIGSTEPBACK': { name: 'Chapter or big step back',  method: 'Input.ExecuteAction',  params: { action: 'chapterorbigstepback' } },
	'CMD_NEXTSCENE': { name: 'Next scene',  method: 'Input.ExecuteAction',  params: { action: 'nextscene' } },
	'CMD_PREVIOUSSCENE': { name: 'Previous scene',  method: 'Input.ExecuteAction',  params: { action: 'previousscene' } },
	'CMD_SKIPNEXT': { name: 'Skip next', method: 'Input.ExecuteAction', params: { action: 'skipnext' } },
	'CMD_SKIPPREVIOUS': { name: 'Skip previous', method: 'Input.ExecuteAction', params: { action: 'skipprevious' } },
	'CMD_SMALLSTEPBACK': { name: 'Small step back',  method: 'Input.ExecuteAction',  params: { action: 'smallstepback' } },
	'CMD_STEPBACK': { name: 'Step back',  method: 'Input.ExecuteAction',  params: { action: 'stepback' } },
	'CMD_STEPFORWARD': { name: 'Step forward',  method: 'Input.ExecuteAction',  params: { action: 'stepforward' } },
	'CMD_AUDIODELAY': { name: 'Audio delay', method: 'Input.ExecuteAction', params: { action: 'audiodelay' } },
	'CMD_AUDIODELAYPLUS': { name: 'Audio delay plus', method: 'Input.ExecuteAction', params: { action: 'audiodelayplus' } },
	'CMD_AUDIODELAYMINUS': { name: 'Audio delay minus', method: 'Input.ExecuteAction', params: { action: 'audiodelayminus' } },
	'CMD_AUDIONEXTLANGUAGE': { name: 'Audio language', method: 'Input.ExecuteAction', params: { action: 'audionextlanguage' } },
	'CMD_AUDIOTOGGLEDIGITAL': { name: 'Toggle digital audio', method: 'Input.ExecuteAction', params: { action: 'audiotoggledigital' } },
	'CMD_MUTE': { name: 'Mute', method: 'Input.ExecuteAction', params: { action: 'mute' } },
	'CMD_VOLUMEUP': { name: 'Volume up', method: 'Input.ExecuteAction', params: { action: 'volumeup' } },
 	'CMD_VOLUMEDOWN': { name: 'Volume down', method: 'Input.ExecuteAction', params: { action: 'volumedown' } },
	'CMD_VOLUMEAMPLIFICATION': { name: 'Volume amplification', method: 'Input.ExecuteAction', params: { action: 'volumeamplification' } },
	'CMD_VOLAMPUP': { name: 'Volume amplification up', method: 'Input.ExecuteAction', params: { action: 'volampup' } },
	'CMD_VOLAMPDOWN': { name: 'Volume amplification down', method: 'Input.ExecuteAction', params: { action: 'volampdown' } },
	'CMD_FULLSCREEN': { name: 'Full screen',  method: 'Input.ExecuteAction',  params: { action: 'fullscreen' } },
	'CMD_ASPECTRATIO': { name: 'Aspect ratio',  method: 'Input.ExecuteAction',  params: { action: 'aspectratio' } },
	// 'CMD_INCREASEPAR': { name: 'Increase pixel aspect ratio', method: 'Input.ExecuteAction', params: { action: 'increasepar' } },
	// 'CMD_DECREASEPAR': { name: 'Decrease pixel aspect ratio', method: 'Input.ExecuteAction', params: { action: 'decreasepar' } },
	// 'CMD_NEXTCALIBRATION': { name: 'Next calibration', method: 'Input.ExecuteAction', params: { action: 'nextcalibration' } },
	// 'CMD_RESETCALIBRATION': { name: 'Reset calibration', method: 'Input.ExecuteAction', params: { action: 'resetcalibration' } },
	'CMD_NEXTRESOLUTION': { name: 'Next resolution', method: 'Input.ExecuteAction', params: { action: 'nextresolution' } },
	'CMD_VERTICALSHIFTUP': { name: 'Vertical shift up', method: 'Input.ExecuteAction', params: { action: 'verticalshiftup' } },
	'CMD_VERTICALSHIFTDOWN': { name: 'Vertical shift down', method: 'Input.ExecuteAction', params: { action: 'verticalshiftdown' } },
	'CMD_STEREOMODE': { name: 'Stereo mode', method: 'Input.ExecuteAction', params: { action: 'stereomode' } },
	'CMD_NEXTSTEREOMODE': { name: 'Next stereo mode', method: 'Input.ExecuteAction', params: { action: 'nextstereomode' } },
	'CMD_PREVIOUSSTEREOMODE': { name: 'Previous stereo mode', method: 'Input.ExecuteAction', params: { action: 'previousstereomode' } },
	'CMD_STEREOMODETOMONO': { name: 'Stereo mode to mono', method: 'Input.ExecuteAction', params: { action: 'stereomodetomono' } },
	'CMD_TOGGLEFULLSCREEN': { name: 'Toggle full screen',  method: 'Input.ExecuteAction',  params: { action: 'togglefullscreen' } },
	'CMD_TOGGLESTEREOMODE': { name: 'Toggle stereo mode', method: 'Input.ExecuteAction', params: { action: 'togglestereomode' } },
	// 'CMD_ZOOMIN': { name: 'Zoom in',  method: 'Input.ExecuteAction',  params: { action: 'zoomin' } },
	// 'CMD_ZOOMOUT': { name: 'Zoom out',  method: 'Input.ExecuteAction',  params: { action: 'zoomout' } },
	// 'CMD_ZOOMNORMAL': { name: 'Zoom normal',  method: 'Input.ExecuteAction',  params: { action: 'zoomnormal' } },
	// 'CMD_ZOOMLEVEL1': { name: 'Zoom level 1',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel1' } },
	// 'CMD_ZOOMLEVEL2': { name: 'Zoom level 2',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel2' } },
	// 'CMD_ZOOMLEVEL3': { name: 'Zoom level 3',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel3' } },
	// 'CMD_ZOOMLEVEL4': { name: 'Zoom level 4',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel4' } },
	// 'CMD_ZOOMLEVEL5': { name: 'Zoom level 5',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel5' } },
	// 'CMD_ZOOMLEVEL6': { name: 'Zoom level 6',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel6' } },
	// 'CMD_ZOOMLEVEL7': { name: 'Zoom level 7',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel7' } },
	// 'CMD_ZOOMLEVEL8': { name: 'Zoom level 8',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel8' } },
	// 'CMD_ZOOMLEVEL9': { name: 'Zoom level 9',  method: 'Input.ExecuteAction',  params: { action: 'zoomlevel9' } },
	// 'CMD_FILTER': { name: 'Filter',  method: 'Input.ExecuteAction',  params: { action: 'filter' } },
	// 'CMD_FILTERCLEAR': { name: 'Filter clear',  method: 'Input.ExecuteAction',  params: { action: 'filterclear' } },
	// 'CMD_FILTERSMS2': { name: 'Filter SMS 2',  method: 'Input.ExecuteAction',  params: { action: 'filtersms2' } },
	// 'CMD_FILTERSMS3': { name: 'Filter SMS 3',  method: 'Input.ExecuteAction',  params: { action: 'filtersms3' } },
	// 'CMD_FILTERSMS4': { name: 'Filter SMS 4',  method: 'Input.ExecuteAction',  params: { action: 'filtersms4' } },
	// 'CMD_FILTERSMS5': { name: 'Filter SMS 5',  method: 'Input.ExecuteAction',  params: { action: 'filtersms5' } },
	// 'CMD_FILTERSMS6': { name: 'Filter SMS 6',  method: 'Input.ExecuteAction',  params: { action: 'filtersms6' } },
	// 'CMD_FILTERSMS7': { name: 'Filter SMS 7',  method: 'Input.ExecuteAction',  params: { action: 'filtersms7' } },
	// 'CMD_FILTERSMS8': { name: 'Filter SMS 8',  method: 'Input.ExecuteAction',  params: { action: 'filtersms8' } },
	// 'CMD_FILTERSMS9': { name: 'Filter SMS 9',  method: 'Input.ExecuteAction',  params: { action: 'filtersms9' } },
	// 'CMD_JUMPSMS2': { name: 'Jump SMS 2',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms2' } },
	// 'CMD_JUMPSMS3': { name: 'Jump SMS 3',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms3' } },
	// 'CMD_JUMPSMS4': { name: 'Jump SMS 4',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms4' } },
	// 'CMD_JUMPSMS5': { name: 'Jump SMS 5',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms5' } },
	// 'CMD_JUMPSMS6': { name: 'Jump SMS 6',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms6' } },
	// 'CMD_JUMPSMS7': { name: 'Jump SMS 7',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms7' } },
	// 'CMD_JUMPSMS8': { name: 'Jump SMS 8',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms8' } },
	// 'CMD_JUMPSMS9': { name: 'Jump SMS 9',  method: 'Input.ExecuteAction',  params: { action: 'jumpsms9' } },
	// 'CMD_NUMBER0': { name: 'Number 0', method: 'Input.ExecuteAction', params: { action: 'number0' } },
 	// 'CMD_NUMBER1': { name: 'Number 1', method: 'Input.ExecuteAction', params: { action: 'number1' } },
 	// 'CMD_NUMBER2': { name: 'Number 2', method: 'Input.ExecuteAction', params: { action: 'number2' } },
 	// 'CMD_NUMBER3': { name: 'Number 3', method: 'Input.ExecuteAction', params: { action: 'number3' } },
 	// 'CMD_NUMBER4': { name: 'Number 4', method: 'Input.ExecuteAction', params: { action: 'number4' } },
 	// 'CMD_NUMBER5': { name: 'Number 5', method: 'Input.ExecuteAction', params: { action: 'number5' } },
 	// 'CMD_NUMBER6': { name: 'Number 6', method: 'Input.ExecuteAction', params: { action: 'number6' } },
 	// 'CMD_NUMBER7': { name: 'Number 7', method: 'Input.ExecuteAction', params: { action: 'number7' } },
 	// 'CMD_NUMBER8': { name: 'Number 8', method: 'Input.ExecuteAction', params: { action: 'number8' } },
 	// 'CMD_NUMBER9': { name: 'Number 9', method: 'Input.ExecuteAction', params: { action: 'number9' } },
	// 'CMD_PREVIOUSPICTURE': { name: 'Previous picture',  method: 'Input.ExecuteAction',  params: { action: 'previouspicture' } },
	// 'CMD_NEXTPICTURE': { name: 'Next picture',  method: 'Input.ExecuteAction',  params: { action: 'nextpicture' } },
	// 'CMD_ROTATE': { name: 'Rotate', method: 'Input.ExecuteAction', params: { action: 'rotate' } },
	// 'CMD_ROTATECCW': { name: 'Rotate counter-clockwise', method: 'Input.ExecuteAction', params: { action: 'rotateccw' } },
	'CMD_CREATEBOOKMARK': { name: 'Create bookmark', method: 'Input.ExecuteAction', params: { action: 'createbookmark' } },
	'CMD_CREATEEPISODEBOOKMARK': { name: 'Create episode bookmark', method: 'Input.ExecuteAction', params: { action: 'createepisodebookmark' } },
	'CMD_CYCLESUBTITLE': { name: 'Cycle subtitle',  method: 'Input.ExecuteAction',  params: { action: 'cyclesubtitle' } },
	'CMD_NEXTSUBTITLE': { name: 'Subtitle', method: 'Input.ExecuteAction', params: { action: 'nextsubtitle' } },
	'CMD_SHOWSUBTITLES': { name: 'Show subtitles',  method: 'Input.ExecuteAction',  params: { action: 'showsubtitles' } },
	// 'CMD_SUBTITLEALIGN': { name: 'Subtitle align', method: 'Input.ExecuteAction', params: { action: 'subtitlealign' } },
	// 'CMD_SUBTITLEDELAY': { name: 'Subtitle delay', method: 'Input.ExecuteAction', params: { action: 'subtitledelay' } },
	// 'CMD_SUBTITLEDELAYMINUS': { name: 'Subtitle delay minus', method: 'Input.ExecuteAction', params: { action: 'subtitledelayminus' } },
	// 'CMD_SUBTITLEDELAYPLUS': { name: 'Subtitle delay plus', method: 'Input.ExecuteAction', params: { action: 'subtitledelayplus' } },
	// 'CMD_SUBTITLESHIFTDOWN': { name: 'Subtitle shift down', method: 'Input.ExecuteAction', params: { action: 'subtitleshiftdown' } },
	// 'CMD_SUBTITLESHIFTUP': { name: 'Subtitle shift up', method: 'Input.ExecuteAction', params: { action: 'subtitleshiftup' } },
	// 'CMD_LEFTCLICK': { name: 'Left click', method: 'Input.ExecuteAction', params: { action: 'leftclick' } },
	// 'CMD_RIGHTCLICK': { name: 'Right click', method: 'Input.ExecuteAction', params: { action: 'rightclick' } },
	// 'CMD_MIDDLECLICK': { name: 'Middle click', method: 'Input.ExecuteAction', params: { action: 'middleclick' } },
	// 'CMD_LONGCLICK': { name: 'Long click', method: 'Input.ExecuteAction', params: { action: 'longclick' } },
	// 'CMD_DOUBLECLICK': { name: 'Double click', method: 'Input.ExecuteAction', params: { action: 'doubleclick' } },
	// 'CMD_WHEELDOWN': { name: 'Mouse wheel down', method: 'Input.ExecuteAction', params: { action: 'wheeldown' } },
	// 'CMD_WHEELUP': { name: 'Mouse wheel up', method: 'Input.ExecuteAction', params: { action: 'wheelup' } },
	// 'CMD_MOUSEDRAG': { name: 'Mouse drag', method: 'Input.ExecuteAction', params: { action: 'mousedrag' } },
	// 'CMD_MOUSEMOVE': { name: 'Mouse move', method: 'Input.ExecuteAction', params: { action: 'mousemove' } },
	// 'CMD_LONGPRESS': { name: 'Long press', method: 'Input.ExecuteAction', params: { action: 'longpress' } },
	// 'CMD_PANGESTURE': { name: 'Pan gesture', method: 'Input.ExecuteAction', params: { action: 'pangesture' } },
	// 'CMD_ROTATEGESTURE': { name: 'Rotate gesture', method: 'Input.ExecuteAction', params: { action: 'rotategesture' } },
	// 'CMD_SWIPEDOWN': { name: 'Swipe down', method: 'Input.ExecuteAction', params: { action: 'swipedown' } },
	// 'CMD_SWIPELEFT': { name: 'Swipe left', method: 'Input.ExecuteAction', params: { action: 'swipeleft' } },
	// 'CMD_SWIPERIGHT': { name: 'Swipe right', method: 'Input.ExecuteAction', params: { action: 'swiperight' } },
	// 'CMD_SWIPEUP': { name: 'Swipe up', method: 'Input.ExecuteAction', params: { action: 'swipeup' } },
	// 'CMD_TAP': { name: 'Tap', method: 'Input.ExecuteAction', params: { action: 'tap' } },
	// 'CMD_ZOOMGESTURE': { name: 'Zoom gesture',  method: 'Input.ExecuteAction',  params: { action: 'zoomgesture' } },
	// 'CMD_CURSORLEFT': { name: 'Cursor left', method: 'Input.ExecuteAction', params: { action: 'cursorleft' } },
	// 'CMD_CURSORRIGHT': { name: 'Cursor right', method: 'Input.ExecuteAction', params: { action: 'cursorright' } },
	'CMD_BACKSPACE': { name: 'Backspace',  method: 'Input.ExecuteAction',  params: { action: 'backspace' } },
	'CMD_ENTER': { name: 'Enter',  method: 'Input.ExecuteAction',  params: { action: 'enter' } },
	'CMD_HIGHLIGHT': { name: 'Highlight',  method: 'Input.ExecuteAction',  params: { action: 'highlight' } },
	'CMD_FIRSTPAGE': { name: 'First page', method: 'Input.ExecuteAction', params: { action: 'firstpage' } },
	'CMD_LASTPAGE': { name: 'Last page',  method: 'Input.ExecuteAction',  params: { action: 'lastpage' } },
	'CMD_MOVEITEMUP': { name: 'Move item up',  method: 'Input.ExecuteAction',  params: { action: 'moveitemup' } },
	'CMD_MOVEITEMDOWN': { name: 'Move item down',  method: 'Input.ExecuteAction',  params: { action: 'moveitemdown' } },
	'CMD_PAGEDOWN': { name: 'Page down',  method: 'Input.ExecuteAction',  params: { action: 'pagedown' } },
	'CMD_PAGEUP': { name: 'Page up',  method: 'Input.ExecuteAction',  params: { action: 'pageup' } },
	'CMD_SCROLLUP': { name: 'Scroll up',  method: 'Input.ExecuteAction',  params: { action: 'scrollup' } },
	'CMD_SCROLLDOWN': { name: 'Scroll down',  method: 'Input.ExecuteAction',  params: { action: 'scrolldown' } },
	'CMD_PARENTDIR': { name: 'Parent directory',  method: 'Input.ExecuteAction',  params: { action: 'parentdir' } },
	'CMD_PARENTFOLDER': { name: 'Parent folder',  method: 'Input.ExecuteAction',  params: { action: 'parentfolder' } },
	'CMD_COPY': { name: 'Copy',  method: 'Input.ExecuteAction',  params: { action: 'copy' } },
	'CMD_DELETE': { name: 'Delete',  method: 'Input.ExecuteAction',  params: { action: 'delete' } },
	'CMD_MOVE': { name: 'Move',  method: 'Input.ExecuteAction',  params: { action: 'move' } },
	'CMD_RENAME': { name: 'Rename',  method: 'Input.ExecuteAction',  params: { action: 'rename' } },
	'CMD_CLOSE': { name: 'Close',  method: 'Input.ExecuteAction',  params: { action: 'close' } },
	'CMD_CONTEXTMENU': { name: 'Context menu', method: 'Input.ExecuteAction', params: { action: 'contextmenu' } },
	'CMD_MENU': { name: 'Menu (sidebar)', method: 'Input.ExecuteAction', params: { action: 'menu' } },
	'CMD_PREVIOUSMENU': { name: 'Previous menu',  method: 'Input.ExecuteAction',  params: { action: 'previousmenu' } },
	// 'CMD_PREVLETTER': { name: 'Previous letter', method: 'Input.ExecuteAction', params: { action: 'prevletter' } },
	// 'CMD_NEXTLETTER': { name: 'Next letter', method: 'Input.ExecuteAction', params: { action: 'nextletter' } },
	// 'CMD_SHIFT': { name: 'Shift', method: 'Input.ExecuteAction', params: { action: 'shift' } },
	// 'CMD_SYMBOLS': { name: 'Symbols', method: 'Input.ExecuteAction', params: { action: 'symbols' } },
	'CMD_LOCKPRESET': { name: 'Lock visualisation preset',  method: 'Input.ExecuteAction',  params: { action: 'lockpreset' } },
	'CMD_NEXTPRESET': { name: 'Next visualisation preset',  method: 'Input.ExecuteAction',  params: { action: 'nextpreset' } },
	'CMD_PREVIOUSPRESET': { name: 'Previous visualisation preset',  method: 'Input.ExecuteAction',  params: { action: 'previouspreset' } },
	'CMD_RANDOMPRESET': { name: 'Random visualisation preset',  method: 'Input.ExecuteAction',  params: { action: 'randompreset' } },
	'CMD_SHOWPRESET': { name: 'Show visualisation preset',  method: 'Input.ExecuteAction',  params: { action: 'showpreset' } },
	'CMD_CODECINFO': { name: 'Codec info',  method: 'Input.ExecuteAction',  params: { action: 'codecinfo' } },
	'CMD_PLAYERDEBUG': { name: 'Player debug info',  method: 'Input.ExecuteAction',  params: { action: 'playerdebug' } },
	'CMD_PLAYERPROCESSINFO': { name: 'Player process info',  method: 'Input.ExecuteAction',  params: { action: 'playerprocessinfo' } },
	'CMD_GUIPROFILE': { name: 'GUI profile',  method: 'Input.ExecuteAction',  params: { action: 'guiprofile' } },
	'CMD_OSD': { name: 'OSD', method: 'Input.ExecuteAction', params: { action: 'osd' } },
	'CMD_SHOWTIME': { name: 'Show time',  method: 'Input.ExecuteAction',  params: { action: 'showtime' } },
	'CMD_SHOWTIMERRULE': { name: 'Show timer rule', method: 'Input.ExecuteAction', params: { action: 'showtimerrule' } },
	'CMD_SHOWVIDEOMENU': { name: 'Show video menu',  method: 'Input.ExecuteAction',  params: { action: 'showvideomenu' } },
	'CMD_INCREASERATING': { name: 'Increase rating',  method: 'Input.ExecuteAction',  params: { action: 'increaserating' } },
	'CMD_DECREASERATING': { name: 'Decrease rating',  method: 'Input.ExecuteAction',  params: { action: 'decreaserating' } },
	'CMD_SETRATING': { name: 'Set rating',  method: 'Input.ExecuteAction',  params: { action: 'setrating' } },
	'CMD_INCREASEVISRATING': { name: 'Increase visrating',  method: 'Input.ExecuteAction',  params: { action: 'increasevisrating' } },
	'CMD_DECREASEVISRATING': { name: 'Decrease visrating',  method: 'Input.ExecuteAction',  params: { action: 'decreasevisrating' } },
	'CMD_ERROR': { name: 'Error', method: 'Input.ExecuteAction', params: { action: 'error' } },
	'CMD_NOOP': { name: 'Nothing', method: 'Input.ExecuteAction', params: { action: 'noop' } },
	'CMD_RELOADKEYMAPS': { name: 'Reload keymaps',  method: 'Input.ExecuteAction',  params: { action: 'reloadkeymaps' } },
	'CMD_SCANITEM': { name: 'Scan item',  method: 'Input.ExecuteAction',  params: { action: 'scanitem' } },
	'CMD_SCREENSHOT': { name: 'Screenshot',  method: 'Input.ExecuteAction',  params: { action: 'screenshot' } },
	'CMD_PLAYLIST': { name: 'Playlist',  method: 'Input.ExecuteAction',  params: { action: 'playlist' } },
	'CMD_PLAYPVR': { name: 'Play PVR',  method: 'Input.ExecuteAction',  params: { action: 'playpvr' } },
	'CMD_PLAYPVRRADIO': { name: 'Play PVR radio',  method: 'Input.ExecuteAction',  params: { action: 'playpvrradio' } },
	'CMD_PLAYPVRTV': { name: 'Play PVR TV',  method: 'Input.ExecuteAction',  params: { action: 'playpvrtv' } },
	'CMD_QUEUE': { name: 'Queue',  method: 'Input.ExecuteAction',  params: { action: 'queue' } },
	'CMD_SETTINGSLEVELCHANGE': { name: 'Settings level change', method: 'Input.ExecuteAction', params: { action: 'settingslevelchange' } },
	'CMD_SETTINGSRESET': { name: 'Settings reset', method: 'Input.ExecuteAction', params: { action: 'settingsreset' } },
	'CMD_SWITCHPLAYER': { name: 'Switch player',  method: 'Input.ExecuteAction',  params: { action: 'switchplayer' } },
	'CMD_TOGGLECOMMSKIP': { name: 'Toggle comm skip', method: 'Input.ExecuteAction', params: { action: 'togglecommskip' } },
	'CMD_TOGGLEWATCHED': { name: 'Toggle watched state',  method: 'Input.ExecuteAction',  params: { action: 'togglewatched' } },

	/*
	 *	Useful API methods
	 */
	 // Power
	'CMD_POWER_ON': { name: 'Power on', method: 'WOL' },
	'CMD_POWER_OFF': { name: 'Power off', method: 'System.Shutdown' },
	// Windows
	// * https://kodi.wiki/view/Window_IDs
	// * https://kodi.wiki/view/JSON-RPC_API/v9#GUI.Window
	'CMD_WINDOW_HOME': { name: 'Activate window: Home', method: 'GUI.ActivateWindow', params: { window: 'home' } },
	'CMD_WINDOW_MUSIC': { name: 'Activate window: Music', method: 'GUI.ActivateWindow', params: { window: 'music' } },
	'CMD_WINDOW_VIDEOS': { name: 'Activate window: Videos', method: 'GUI.ActivateWindow', params: { window: 'videos' } },
	'CMD_WINDOW_FULLSCREEN_LIVE_TV': { name: 'Activate window: Live TV', method: 'GUI.ActivateWindow', params: { window: 'fullscreenlivetv' } },
	'CMD_WINDOW_FULLSCREEN_VIDEO': { name: 'Activate window: Fullscreen video', method: 'GUI.ActivateWindow', params: { window: 'fullscreenvideo' } },
	'CMD_WINDOW_TVRECORDINGS': { name: 'Activate window: TV Recordings', method: 'GUI.ActivateWindow', params: { window: 'tvrecordings' } },
	// Player
	'CMD_REVERSE': { name: 'Reverse', method: 'Player.SetSpeed', params: { playerid: 1, speed: -2 } },
	'CMD_FORWARD': { name: 'Forward', method: 'Player.SetSpeed', params: { playerid: 1, speed: 2 } },
	'CMD_PREVIOUS': { name: 'Previous', method: 'Player.GoTo', params: { playerid: 1, to: 'previous' } },
	'CMD_NEXT': { name: 'Next', method: 'Player.GoTo', params: { playerid: 1, to: 'next' } },
};

// Button translations for different windows
// See https://github.com/xbmc/xbmc/blob/master/system/keymaps/remote.xml
const keymap = {
  // Full screen live tv
  '10800': {
    'CURSOR LEFT': 'STEPBACK',
		'CMD_LEFT': 'STEPBACK',
		'CURSOR RIGHT': 'STEPFORWARD',
		'CMD_RIGHT': 'STEPFORWARD',
  },
  // Full screen radio
  '10800': {
		'CURSOR LEFT': 'STEPBACK',
		'CMD_LEFT': 'STEPBACK',
		'CURSOR RIGHT': 'STEPFORWARD',
		'CMD_RIGHT': 'STEPFORWARD',
  },
  // Full screen video
  '12005': {
		'CURSOR LEFT': 'STEPBACK',
		'CMD_LEFT': 'STEPBACK',
		'CURSOR RIGHT': 'STEPFORWARD',
		'CMD_RIGHT': 'STEPFORWARD',
		'CURSOR UP': 'CHAPTERORBIGSTEPFORWARD',
		'CMD_UP': 'CHAPTERORBIGSTEPFORWARD',
		'CURSOR DOWN': 'CHAPTERORBIGSTEPBACK',
		'CMD_DOWN': 'CHAPTERORBIGSTEPBACK',
  },
};

// This is a list of keys from lib/kodiCommands to be included as buttons in the driver
const buttons = [
	'CMD_ASPECTRATIO',
	'CMD_AUDIODELAY',
	'CMD_AUDIODELAYMINUS',
	'CMD_AUDIODELAYPLUS',
	'CMD_AUDIONEXTLANGUAGE',
	'CMD_AUDIOTOGGLEDIGITAL',
	'CMD_BACK',
	'CMD_BACKSPACE',
	'CMD_BIGSTEPBACK',
	'CMD_BIGSTEPFORWARD',
	'CMD_BLUE',
	'CMD_CHANNELDOWN',
	'CMD_CHANNELUP',
	'CMD_CHAPTERORBIGSTEPBACK',
	'CMD_CHAPTERORBIGSTEPFORWARD',
	'CMD_CLOSE',
	'CMD_CODECINFO',
	'CMD_CONTEXTMENU',
	'CMD_COPY',
	'CMD_CREATEBOOKMARK',
	'CMD_CREATEEPISODEBOOKMARK',
	'CMD_CYCLESUBTITLE',
	'CMD_DECREASERATING',
	'CMD_DECREASEVISRATING',
	'CMD_DELETE',
	'CMD_DOWN',
	'CMD_ENTER',
	'CMD_ERROR',
	'CMD_FASTFORWARD',
	'CMD_FIRSTPAGE',
	'CMD_FORWARD',
	'CMD_FULLSCREEN',
	'CMD_GREEN',
	'CMD_GUIPROFILE',
	'CMD_HIGHLIGHT',
	'CMD_HOME',
	'CMD_INCREASERATING',
	'CMD_INCREASEVISRATING',
	'CMD_INFO',
	'CMD_LASTPAGE',
	'CMD_LEFT',
	'CMD_LOCKPRESET',
	'CMD_MENU',
	'CMD_MOVE',
	'CMD_MOVEITEMDOWN',
	'CMD_MOVEITEMUP',
	'CMD_MUTE',
	'CMD_NEXT',
	'CMD_NEXTCHANNELGROUP',
	'CMD_NEXTPRESET',
	'CMD_NEXTRESOLUTION',
	'CMD_NEXTSCENE',
	'CMD_NEXTSTEREOMODE',
	'CMD_NEXTSUBTITLE',
	'CMD_NOOP',
	'CMD_OSD',
	'CMD_PAGEDOWN',
	'CMD_PAGEUP',
	'CMD_PARENTDIR',
	'CMD_PARENTFOLDER',
	'CMD_PAUSE',
	'CMD_PLAY',
	'CMD_PLAYERDEBUG',
	'CMD_PLAYERPROCESSINFO',
	'CMD_PLAYLIST',
	'CMD_PLAYPAUSE',
	'CMD_PLAYPVR',
	'CMD_PLAYPVRRADIO',
	'CMD_PLAYPVRTV',
	'CMD_POWER_OFF',
	'CMD_POWER_ON',
	'CMD_PREVIOUS',
	'CMD_PREVIOUSCHANNELGROUP',
	'CMD_PREVIOUSMENU',
	'CMD_PREVIOUSPRESET',
	'CMD_PREVIOUSSCENE',
	'CMD_PREVIOUSSTEREOMODE',
	'CMD_QUEUE',
	'CMD_RANDOMPRESET',
	'CMD_RECORD',
	'CMD_RED',
	'CMD_RELOADKEYMAPS',
	'CMD_RENAME',
	'CMD_REVERSE',
	'CMD_REWIND',
	'CMD_RIGHT',
	'CMD_SCANITEM',
	'CMD_SCREENSHOT',
	'CMD_SCROLLDOWN',
	'CMD_SCROLLUP',
	'CMD_SELECT',
	'CMD_SETRATING',
	'CMD_SETTINGSLEVELCHANGE',
	'CMD_SETTINGSRESET',
	'CMD_SHOWCODEC',
	'CMD_SHOWOSD',
	'CMD_SHOWPLAYERPROCESSINFO',
	'CMD_SHOWPRESET',
	'CMD_SHOWSUBTITLES',
	'CMD_SHOWTIME',
	'CMD_SHOWTIMERRULE',
	'CMD_SHOWVIDEOMENU',
	'CMD_SKIPNEXT',
	'CMD_SKIPPREVIOUS',
	'CMD_SMALLSTEPBACK',
	'CMD_STEPBACK',
	'CMD_STEPFORWARD',
	'CMD_STEREOMODE',
	'CMD_STEREOMODETOMONO',
	'CMD_STOP',
	'CMD_SWITCHPLAYER',
	'CMD_TOGGLECOMMSKIP',
	'CMD_TOGGLEFULLSCREEN',
	'CMD_TOGGLESTEREOMODE',
	'CMD_TOGGLEWATCHED',
	'CMD_UP',
	'CMD_VERTICALSHIFTDOWN',
	'CMD_VERTICALSHIFTUP',
	'CMD_VOLAMPDOWN',
	'CMD_VOLAMPUP',
	'CMD_VOLUMEAMPLIFICATION',
	'CMD_VOLUMEDOWN',
	'CMD_VOLUMEUP',
	'CMD_WINDOW_FULLSCREEN_LIVE_TV',
	'CMD_WINDOW_FULLSCREEN_VIDEO',
	'CMD_WINDOW_HOME',
	'CMD_WINDOW_MUSIC',
	'CMD_WINDOW_TVRECORDINGS',
	'CMD_WINDOW_VIDEOS',
	'CMD_YELLOW'
];

module.exports = { commands, buttons, keymap };
